from PIL import Image

def create_icons():
    try:
        img = Image.open("assets/store/raw_icon.png")
        
        # We assume the image is square as it was generated by the tool.
        # Resize to 80x80
        img_80 = img.resize((80, 80), Image.Resampling.LANCZOS)
        img_80.save("assets/store/icon_80x80.png")
        
        # Resize to 144x144
        img_144 = img.resize((144, 144), Image.Resampling.LANCZOS)
        img_144.save("assets/store/icon_144x144.png")
        
        print("Successfully generated icon_80x80.png and icon_144x144.png")
    except Exception as e:
        print("Error creating icons:", e)

create_icons()
